In [10]:
%matplotlib inline
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import string
import toolz as tz
import toolz.curried as c
import scipy.linalg as la

In [1]:
print([i**2 for i in range(10) if i % 2 == 0])
print([(i,j) for i in range(3) for j in range(4)])

[0, 4, 16, 36, 64]
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]


In [2]:
(i for i in range(10) if i % 3 == 0)

<generator object <genexpr> at 0x7f0c5c091c50>

In [9]:
sorted(['apple','banana','grape','pear'], key=lambda s: s.count('a'))

['apple', 'grape', 'pear', 'banana']

In [3]:
reversed([3,1,5,2,4])

In [4]:
%load_ext rpy2.ipython
iris = %R iris

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [5]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [35]:
%%R
pnorm(0,1,2)

[1] 0.3085375


In [6]:
%%R -o iris
head(iris)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa


### Note 2

In [7]:
def f(a, b, c, *args, **kwargs):
    return a, b, c, args, kwargs

In [8]:
f(1,2,3,4,5,x=3,y=1)

(1, 2, 3, (4, 5), {'x': 3, 'y': 1})

In [12]:
from functools import reduce

xs = range(10)
reduce(lambda x,y: x+y,xs,10)

55

In [14]:
from functools import partial, lru_cache
def f(a, b, c):
    return a + b + c
g = partial(f, b = 2, c=3)
g(1)

6

In [15]:
@lru_cache(3)
def fib(n, trace=False):
    if trace:
        print("fib(%d)" % n, end=',')
    if n <= 2:
        return 1
    else:
        return fib(n-1, trace) + fib(n-2, trace)

In [16]:
%timeit -r1 -n100 fib(20)

363 ns ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)


In [3]:
dna = np.random.choice(list('ACTG'), (10,80), p=[.1,.2,.3,.4])

In [21]:
np.random.normal(0, 1, (2,3))

array([[ 1.25451215,  0.50429632,  0.23176937],
       [ 0.39677664, -0.09065209, -0.65628185]])

In [23]:
x = np.arange(20).reshape((4,5))
x[np.ix_([0,2], [0,3])]

array([[ 0,  3],
       [10, 13]])

In [24]:
np.nonzero(x)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

A slice is a view, not a copy

In [25]:
x = np.arange(1, 13)
#x[:,None] * x[None,:]
np.outer(x,x)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [36]:
np.log1p(xs)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509])

In [41]:
%magic -brief

In [42]:
s = "  Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37\n"
s.strip()

'Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37'

In [43]:
s.lower(),s.upper(),s.title()

('  avoid taking unnecessary gambles. lucky numbers: 12, 15, 23, 28, 37\n',
 '  AVOID TAKING UNNECESSARY GAMBLES. LUCKY NUMBERS: 12, 15, 23, 28, 37\n',
 '  Avoid Taking Unnecessary Gambles. Lucky Numbers: 12, 15, 23, 28, 37\n')

In [44]:
s.startswith('Avoid')

False

In [ ]:
'-'.join(s.split())

In [55]:
table = str.maketrans('','' , string.punctuation)
words = s.lower().strip().translate(table)
words

'avoid taking unnecessary gambles lucky numbers 12 15 23 28 37'

In [56]:
from collections import Counter

bag = Counter(words.split())
bag

Counter({'12': 1,
         '15': 1,
         '23': 1,
         '28': 1,
         '37': 1,
         'avoid': 1,
         'gambles': 1,
         'lucky': 1,
         'numbers': 1,
         'taking': 1,
         'unnecessary': 1})

One hot encoding

In [62]:
idx = 0
index = {}
for word in words:
    if not word in index:
        index[word] = idx
        idx += 1
vs = np.array([index[word] for word in words])
n = len(vs)
p = len(index)
m = np.zeros((n,p), dtype='int')
i = np.arange(len(vs))
m[i, vs] = 1
m

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

Note 7B Vectors

In [5]:
x = np.random.random((5,1))
x/np.linalg.norm(x)

array([[ 0.09577099],
       [ 0.52095599],
       [ 0.46292725],
       [ 0.70308287],
       [ 0.10395003]])

In [8]:
np.linalg.inv(np.random.random((4,4)))

array([[ 1.26956029,  0.89196405, -0.61542159, -1.59765107],
       [ 1.52905219, -2.81062481,  4.42516885, -1.00043914],
       [ 0.13978625, -0.76077207,  0.09585292,  1.18234153],
       [-1.65461057,  2.26577533, -1.92762077,  1.15292302]])

import scipy.linalg as la

LU,P = la.lu_factor(A)    
x = lu_solve((LU,P),b)

C1 = la.cho_factor(A)   
la.cho_solve(C1, b)

In [68]:
A = np.array([
    [1,2,3,3],
    [2,0,6,2],
    [3,4,9,7]
])
U, s, Vt = la.svd(A)
tol = s.max() * max(A.shape) * np.finfo(float).eps
tol
r = np.sum(s > tol)

In [ ]:
#C(A)
U[:, :r]

In [ ]:
#N(AT)
U[:, r:]

In [ ]:
#C(AT)
Vt[:r, :].T

In [ ]:
#N(A)
Vt[r:, :].T

In [ ]:
np.linalg.matrix_rank(A)

In [ ]:
U = A @ V @ np.diag(1/np.diag(S))

How to do Gram-Schmidt?

In [94]:
def normalize(v):
    return v / np.sqrt(v.dot(v))

def gram_schmidt(A):
    n = len(A)
    Q=np.zeros((3,4))
    Q[:, 0] = normalize(A[:, 0])

    for i in range(1, n):
        Ai = A[:, i]
        for j in range(0, i):
            Aj = A[:, j]
            t = Ai.dot(Aj)
            Ai = Ai - t * Aj/(Aj@Aj)
        Q[:, i] = normalize(Ai)
    return Q

In [95]:
gram_schmidt(A)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[ 0.26726124,  0.40824829,         nan,  0.        ],
       [ 0.53452248, -0.81649658,         nan,  0.        ],
       [ 0.80178373,  0.40824829,         nan,  0.        ]])

In [91]:
Q=np.zeros_like(A)
a = np.copy(normalize(A[:, 0]))
Q[:,0] = a
Q

array([[0.26726124, 0.        , 0.        , 0.        ],
       [0.53452248, 0.        , 0.        , 0.        ],
       [0.80178373, 0.        , 0.        , 0.        ]])

In [87]:
Q[:, 0] = a[:]

In [89]:
Q[:,0]

array([0, 0, 0])

In [85]:
a

array([0.26726124, 0.53452248, 0.80178373])

In [60]:
A[:,0]/np.linalg.norm(A[:,0])

array([0.26726124, 0.53452248, 0.80178373])

In [14]:
la.qr(A)

(array([[-0.26726124,  0.40824829, -0.87287156],
        [-0.53452248, -0.81649658, -0.21821789],
        [-0.80178373,  0.40824829,  0.43643578]]),
 array([[-3.74165739e+00, -3.74165739e+00, -1.12249722e+01,
         -7.48331477e+00],
        [ 0.00000000e+00,  2.44948974e+00,  1.22352938e-15,
          2.44948974e+00],
        [ 0.00000000e+00,  0.00000000e+00, -3.77891439e-15,
         -9.43689571e-16]]))

LU

In [ ]:
P,L,U = la.lu(A)
z = P.T @ b
y = la.solve_triangular(L, z, lower=True)
x = la.solve_triangular(U, y, lower=False)

In [ ]:

D = np.diag(np.diag(U))
U = U/np.diag(U)[:, None]
z = P.T @ b
y = la.solve_triangular(L, z, lower=True)
x = la.solve_triangular(D @ U, y, lower=False)


QR

In [ ]:
Q, R = la.qr(A)
y = Q.T @ b
la.solve_triangular(R, y, lower=False)

SVD

In [ ]:
U, s, Vt = la.svd(A)
V = Vt.T
V @ np.diag(1/s) @ U.T @ b

Cholesky

In [ ]:
C = la.cholesky(A, lower=True)
y = la.solve_triangular(C, b, lower=True)
x = la.solve_triangular(C.T, y, lower=False)
la.cho_solve(la.cho_factor(A), b)

Recall that the for similar matrices $A$ and $B$,
$$
AP = PB
$$
so we want to solve $B = P^{-1}AP$.

In [ ]:
#quadratic minimum
la.cho_solve(la.cho_factor(A), -b/2)

In [ ]:
def pdist(xs):
    """Pairwise Euclidean distacne."""
    
    return np.sqrt(np.sum((xs[:, None] - xs[None, :])**2, -1))